version: "3"
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_DEFAULT_BUCKETS: ${MINIO_BUCKET_NAME}
    networks:
      - nodewave-be-test-net
    volumes:
      - minio_data:/nodewave-be-test
    ports:
      - ${MINIO_PORT}:${MINIO_PORT} # S3 API port
      - "9001:9001" # MinIO Console port
networks:
  mynet:
    driver: bridge
volumes:
  minio_data:
    driver: local